import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import ApiFetch from '../components/ApiFetch';
import styles from '../styles/Home.module.css'

export default function Home() {

  const [fetched, setFetched] = useState(null);

  useEffect(() => {
    ApiFetch().then(value => {
      setFetched(value);
    })
  }, [])

  useEffect(() => {
    console.log(fetched);
  }, [fetched]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">
        {fetched}
      </h1>
    </div>
  )
}
