import Head from 'next/head'
import Main from '../components/Main';
import styles from '../styles/Home.module.css'

export default function Home() {

  if (typeof window === 'undefined') {
    // Server sided MYSQL Code, for API saving on DB
  }
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Bitcoin Tracking App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </div>
  )
}
